# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.2

EAPI=8

CRATES="
	binfarce@0.2.1
	fallible-iterator@0.2.0
	json@0.12.4
	libc@0.2.126
	memmap2@0.5.4
	multimap@0.8.3
	pdb@0.7.0
	pico-args@0.5.0
	regex-syntax@0.6.26
	regex@1.5.6
	scroll@0.10.2
	term_size@0.3.2
	uuid@0.8.2
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
"

inherit cargo

DESCRIPTION="Find out what takes most of the space in your executable."
HOMEPAGE="https://github.com/RazrFalcon/cargo-bloat"
SRC_URI="
	https://github.com/RazrFalcon/cargo-bloat/archive/refs/tags/v${PV} -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" MIT"
SLOT="0"
KEYWORDS="~amd64"
