# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	ansi_term@0.11.0
	anyhow@1.0.31
	approx@0.3.2
	atty@0.2.14
	autocfg@1.0.0
	bitflags@1.2.1
	bumpalo@3.4.0
	cast@0.2.3
	cfg-if@0.1.10
	cfg-if@1.0.0
	chrono@0.4.13
	clap@2.33.1
	criterion-plot@0.4.3
	crossbeam-deque@0.7.3
	crossbeam-epoch@0.8.2
	crossbeam-queue@0.2.3
	crossbeam-utils@0.7.2
	either@1.5.3
	getrandom@0.1.14
	half@1.6.0
	hashbrown@0.8.1
	hermit-abi@0.1.15
	indexmap@1.5.0
	itertools@0.9.0
	itoa@0.4.6
	js-sys@0.3.51
	lazy_static@1.4.0
	libc@0.2.72
	linked-hash-map@0.5.3
	linked_hash_set@0.1.3
	log@0.4.11
	maybe-uninit@2.0.0
	memoffset@0.5.5
	num-integer@0.1.43
	num-traits@0.2.14
	num_cpus@1.13.0
	oorandom@11.1.2
	plotters-backend@0.3.2
	plotters-svg@0.3.1
	plotters@0.3.1
	ppv-lite86@0.2.8
	proc-macro2@1.0.28
	quickcheck@0.9.2
	quote@1.0.7
	rand@0.7.3
	rand_chacha@0.2.2
	rand_core@0.5.1
	rand_hc@0.2.0
	rayon-core@1.7.1
	rayon@1.3.1
	rustc_version@0.2.3
	ryu@1.0.5
	same-file@1.0.6
	scopeguard@1.1.0
	semver-parser@0.7.0
	semver@0.9.0
	serde@1.0.114
	serde_cbor@0.11.1
	serde_derive@1.0.114
	serde_json@1.0.56
	simplelog@0.10.0
	strsim@0.8.0
	syn@1.0.74
	termcolor@1.1.0
	textwrap@0.11.0
	time@0.1.43
	tinytemplate@1.1.0
	toml@0.5.6
	unicode-width@0.1.8
	unicode-xid@0.2.1
	vec_map@0.8.2
	walkdir@2.3.1
	wasi@0.9.0+wasi-snapshot-preview1
	wasm-bindgen-backend@0.2.74
	wasm-bindgen-macro-support@0.2.74
	wasm-bindgen-macro@0.2.74
	wasm-bindgen-shared@0.2.74
	wasm-bindgen@0.2.74
	web-sys@0.3.51
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
"

inherit cargo

DESCRIPTION="Cargo extension for running Criterion.rs benchmarks and reporting the results."
HOMEPAGE="https://github.com/criterion-rs/cargo-criterion"
SRC_URI="
	https://github.com/criterion-rs/cargo-criterion/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 MIT"
SLOT="0"
KEYWORDS="~amd64"
